### ISSUE TITLE
Eager mods do not work with one-shot-modifiers

### ISSUE THREAD

**Issue by jasonkena** [getreuer/qmk-keymap#17]
Less of a bug report, more of a need for better documentation I think. The code in the "One-shot mod-tap key" section breaks by default since `MOD_LSFT` is eager by default.

**Comment by getreuer** [comment]
Hi, thank for very much for this report! You are right, there is a bug that the mod gets stuck when it is both eager and used with that one-shot mod-tap trick. I'll submit a fix for this soon.

**Comment by getreuer** [comment]
Commit https://github.com/getreuer/qmk-keymap/commit/393fa0b45d21e72803bd6877f83fe195233429bd should fix this so that eager mods work together with the one-shot mod-tap trick. Thanks again for reporting!
