### ISSUE TITLE
[Bug]Sentence case doesn't work with oneshot shift mod or pre-shifted characters

### ISSUE THREAD

**Issue by drashna** [getreuer/qmk-keymap#57]
## Describe the bug

As title.  I use oneshot mods for shift, and it doesn't work with !/?.  switching to a normal shift works.  But I like my oneshot shifts. 

Also `S(KC_1)` fails to trigger, as well. 

## Information

**Do the keys involved use any of the following features?**
 - [x] Sentence case

**Comment by getreuer** [comment]
Thanks for reporting that, drashna! You are right, one-shot shifts, `S(KC_1)`, `S(KC_SLSH)' are currently overlooked in the default handler. I'll push a fix soon.
