### ISSUE TITLE
Achordion seems to break combos when mod-tap key held

### ISSUE THREAD

**Issue by jdart** [getreuer/qmk-keymap#7]
I used Achordion today and it worked great for the most part but I wasn't able to use mod-tap modifiers with key codes I trigger with a combo. I try to avoid lateral movement with my index fingers, so I use combos for the inner columns of my colemak layout. 

For example I press `f`+`p` to produce a `b`, but when I have `LSFT_T(KC_S)` held, the combo doesn't work and `f`+`p` are output.

Here's a [link to my keymap](https://github.com/jdart/qmk_firmware/blob/master/keyboards/ferris/keymaps/dart-hmr/keymap.c#L60) where you can see how I set things up.

**Comment by getreuer** [comment]
Thanks for the clear report and for sharing your keymap. Much appreciated! I'll look into it.

**Comment by getreuer** [comment]
Sorry, I don't see a way to get Achordion to work properly together with Combos. Combos are handled before the point where userspace code can intercept them, and Combos don't expose APIs that help with this. You could still use Combos and Achordion in the same keymap if combos are pressed only while tap-hold keys aren't held, though that would be hard to do with your keymap, unfortunately. Thanks again for your report.

**Comment by getreuer** [comment]
On second thought, it is possible to detect when an event comes from a Combo and avoid having Achordion act on it. I just pushed a commit that does that. I don't expect this fully solves interoperation with Combos, but in my testing it does seem to help. I hope this works for you too.

**Comment by jdart** [comment]
Thanks for the update, it's working for all the cases I've tried so far 🔥

**Comment by getreuer** [comment]
Fantastic! Glad to hear it =)
