### ISSUE TITLE
Achordion preprocessor for TAP_CODE_DELAY

### ISSUE THREAD

**Issue by filterpaper** [getreuer/qmk-keymap#8]
Wrapping tap delay with pre-processors should cover the use-case where none is set:
```c
#if TAP_CODE_DELAY > 0
      wait_ms(TAP_CODE_DELAY);
#endif
```
https://github.com/getreuer/qmk-keymap/blob/8203f4fb25ba329fc23f4c17d0f7ca64d7fad826/features/achordion.c#L114

**Comment by getreuer** [comment]
Thanks for catching this!
